apiVersion: v2
name: parentchart2
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies: 
- name: common
  version: ">=2.10.0"
  repository: "file://charts/common"
- name: nginx
  version: ">=15.5.0"
  repository: "file://charts/nginx"
  alias: childnginx
  tags:
  - frontend
  import-values:
  - child: service
    parent: nginx2service
  - child: image
    parent: nginx2image
- name: mysql
  version: "~9.10.1"
  repository: "file://charts/mysql"
  alias: childmysql
  tags:
  - backend
  import-values:
  - mychartmysqlData
