apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
data:
  {{- with .Values.myapp.data.config }}
  application-name: {{ .appName }}
  application-type: {{ .appType }}
  {{- end }}