{{- $appversion := .Chart.AppVersion -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap2
data:
{{- range $key, $value  := .Values.myapps.config2 }}
{{- $key | nindent 2 }}: {{ $value }}-{{ $.Chart.Name }}-{{ $appversion }}
{{- end }}