

{{- $chartname := .Chart.Name | quote | upper -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmbasics.resourceName" . }}-deployment
  labels:
    {{/*- template "helmbasics.labels" . */}} 
    {{- include "helmbasics.labels" . | upper }}
  annotations: 
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    # quote functions 
    app.kubernetes.io/managed-by: {{ quote .Release.Service }}
    # pipeline 
    app.kubernetes.io/managed-by: {{ .Release.Service | quote | upper }}
    #default function 
    app.kubernetes.io/name: {{  default "MYRELEASE101"  .Values.releaseName  | quote  }}
    # the leading whitespaces will be ignored  during the rendering
    leading-whitespace: "   {{- .Chart.Name }}    somename"
    ## removing trailing whitespaces
    trailing-whitespace: "   {{ .Chart.Name -}}    somename"  
    ## removing leading and trailing whitepsaces
    leadtrail-whitespace: "   {{- .Chart.Name -}}    somename"
    # ident test
    identtest: "   {{- .Chart.Name | indent 4 -}}  " 
    # new line ident   
    nidenttest: "   {{- .Chart.Name | nindent 10 -}}  "   
spec: 
  # {{- if and .Values.myapp.retail.enableFeature (eq .Values.myapp.env "prod") }}
  # replicas: 6
  # {{- else if or (eq .Values.myapp.env "qa") (eq .Values.myapp.env "dev") }}
  # replicas: 10
  # {{- else if eq .Values.myapp.env "prod"}}
  # replicas: {{ default 4 .Values.replicaCount }}
  # {{- else if eq .Values.myapp.env "uat"}}
  # replicas: {{ default 2 .Values.replicaCount }}
  # {{- else }}
  # replicas: 1
  # {{- end }}
  {{- with .Values.myapp }}
  {{- if not (eq .env "prod") }}
  replicas: 2
  {{- else }}
  replicas: 1
  {{- end }}
  {{- end }}
 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}  
        appManagedBy: {{ $.Release.Service }} 
        chartName: {{ $chartname }}
    {{- end }}
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        ## toYaml functions 
        resources:
        {{- toYaml .Values.resources | nindent 10 }}