{{- range .Values.namespaceArray }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
---
{{- end }}

{{- range $environment := .Values.environments }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ $environment.name }}
---

{{- end }}

