apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-users
data:
  internal_users.yml: |
    _meta:
       type: "internalusers"
       config_version: 2
    admin:
      hash: "$2a$12$tscK7i5yyMeYn/6yEXPtneGhz6mUQYS0ASQACx2B7N5433FvWSPQO"
      reserved: true
      hidden: false
      backend_roles:
        - admin
      description: "admin user"
    admin1:
      hash: "$2a$12$tscK7i5yyMeYn/6yEXPtneGhz6mUQYS0ASQACx2B7N5433FvWSPQO"
      backend_roles:
        - "admin"
      description: "A new demo user"
    kibanaserver:
      hash: "$2a$12$tscK7i5yyMeYn/6yEXPtneGhz6mUQYS0ASQACx2B7N5433FvWSPQO"
      reserved: true
      description: "Demo OpenSearch Dashboards user"
    kibanaro:
      hash: "$2a$12$tscK7i5yyMeYn/6yEXPtneGhz6mUQYS0ASQACx2B7N5433FvWSPQO"
      reserved: false
      backend_roles:
      - "kibanauser"
      - "readall"
      attributes:
        attribute1: "value1"
        attribute2: "value2"
        attribute3: "value3"
      description: "Demo OpenSearch Dashboards read only user, using external role mapping"
