apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshots
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 300Gi
