apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-hooks.fullname" .}}-fail
  labels: 
    {{- include "helm-hooks.labels" . | nindent 4 }}
  annotations: 
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "helm-hooks.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: ducmmy-fail
        image: "alpine:3.20.3"
        command: ["sh","-c","echo it will fail; exit 1"]
