apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-hooks.fullname" .}}-second
  labels: 
    {{- include "helm-hooks.labels" . | nindent 4 }}
  annotations: 
    "helm.sh/hook": pre-upgrade,pre-delete,pre-rollback
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "helm-hooks.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: ducmmy-second-hook
        image: "alpine:3.20.3"
        command: ["sh","-c","echo execuitng some second backup job"]
