# Default values for helmbasics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

releaseName: 
replicaCount:


resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

myapp:
  env: prod
  retail:
    enableFeature: true
  data:
    config:
      appName: myapp1
      appType: webserver
      appTech: HTML
      appDb: mysql

podAnnotations:
  appName: myapp1
  appType: apiserver
  appTech: golang

namespaceArray:
  - name: myapp1
  - name: myapp2
  - name: myapp3
  - name: myapp4


environments:
  - name: dev
  - name: qa
  - name: uat
  - name: prod
  
myapps:
  config1:
    appName: myapp1
    appType: webserver
    appTech: HTML
    appDB: mysql
  config2:
    appName: myapp2
    appType: webserver
    appTech: HTML
    appDB: Postgresql