{{- range $key, $value := .Values.apiApps }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $value.name }}-service.{{ $.Values.namespaceName  }}.svc.cluster.local
  namespace: {{ $.Values.namespaceName }}
spec:
  host: {{ $value.name }}-service.{{ $.Values.namespaceName  }}.svc.cluster.local
  subsets:
    - name: {{ $value.one.model_version }}
      labels:
        version: {{ $value.one.model_version }}
    - name: {{ $value.two.model_version }}
      labels:
        version: {{ $value.two.model_version }}
{{- end }}
