{{- range $key, $value := .Values.apiApps }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $value.name }}-vs
  namespace: {{ $.Values.namespaceName }}
spec:
  hosts:
    - {{ $value.name }}.172.19.8.2.nip.io
  gateways:
    - gateway
  http:
    - route:
        - destination:
            host: {{ $value.name }}-service.{{ $.Values.namespaceName  }}.svc.cluster.local
            port:
              number: {{ $.Values.service.port }}
            subset: {{ $value.one.model_version }}
          {{- if $value.one.active }}
          weight: 100
          {{- else }} 
          weight: 0
          {{- end }}
        - destination:
            host: {{ $value.name }}-service.{{ $.Values.namespaceName  }}.svc.cluster.local
            port:
              number: {{ $.Values.service.port }}
            subset: {{ $value.two.model_version }}
         {{- if $value.two.active }}
          weight: 100
          {{- else }} 
          weight: 0
          {{- end }}
{{- end }}