apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "parentchart2.fullname" . }}-import-implicit
data: 
  serviceType: {{ .Values.nginx2service.type }}
  servicePort: {{ .Values.nginx2service.ports.http }}
