{{- range $key, $value := .Values.apiApps }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $value.name }}-ingress
  namespace: {{ $.Values.namespaceName }}
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $value.ingressHost }}.k8s-{{ $.Values.env }}.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $value.name }}-service
                port:
                  number: 8080
{{- if eq $.Values.ingress.tls.enabled true }}
  tls:
    - hosts:
        - {{ $value.ingressHost }}.k8s-{{ $.Values.env }}.domain.com
      secretName: aks-ingress-tls
{{- end }}
{{- end }}
